### ISSUE TITLE
Not able to run liri-session with yocto version zeus

### ISSUE THREAD

**Issue by ghost** [lirios/session#16]
I built liri-desktop with yocto version zeus and i am not able to start liri Desktop. Did something change ?

root@imx8qmmek:~# liri-session
Liri session manager cannot be run as root!

root@imx8qmmek:~# liri-session -- -platform liri
Liri session manager cannot be run as root!

**Comment by plfiorini** [comment]
For security reasons, Liri doesn't run as root.
Run it as a unprivileged user.

**Comment by ghost** [comment]
I tried to run it as a unprivileged user and got the following error:

neena1@imx8qmmek:/home/root$ liri-session
== Liri Session ==
** https://liri.io
** Bug reports to: https://github.com/lirios/session/issues
** Build: 0.1.0-tarball
Architecture: arm64
liri.session: Failed to register D-Bus service "org.freedesktop.ScreenSaver": No
t connected to D-Bus server
liri.session: Failed to register D-Bus service "io.liri.Launcher": Not connected
 to D-Bus server

I can see that d-bus service is running
neena1@imx8qmmek:/home/root$ systemctl status dbus
* dbus.service - D-Bus System Message Bus
   Loaded: loaded (/lib/systemd/system/dbus.service; static; vendor preset: dis>
   Active: active (running) since Wed 2020-02-12 22:32:30 UTC; 31min ago

What systemd service should i start to run LiriDesktop ?

**Comment by plfiorini** [comment]
That dbus.service is the system bus, but the services are registered in the session bus.
What does the `DBUS_SESSION_BUS_ADDRESS` environment variable contain?
If it's empty or unset, `liri-session` relaunches itself with `dbus-run-session`. Do you have this program?

**Comment by plfiorini** [comment]
Also I recommend, if you haven't done already, to log in with your unprivileged user from a virtual terminal not `sudo` or `su`.

**Comment by ghost** [comment]
I am using the yocto image.
echo $DBUS_SESSION_BUS_ADDRESS
unix:path=/run/user/0/bus

**Comment by plfiorini** [comment]
Clearly indicates that it comes from the root user (`/run/user/0/bus`, the number 0 is the uid of the root user).
Try logging in from a `vt` as your unprivileged user, don't use `sudo` or any equivalent.
